version: 2.1
on:
  push:
    branches:
      - hw-1

jobs:
  build:
    machine:
      image: ubuntu-1604:202104-01

    steps:
      - checkout
      - run:
          name: Installing GCC
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc g++
      - run:
          name: Install CMAKE
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake
      - run:
          name: Install Valgrind
          command: sudo apt-get install -y valgrind
      - run:
          name: Install GoogleTests
          command: |
            sudo apt-get install -y libgtest-dev
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp -R /usr/src/gtest/*.a /usr/lib/x86_64-linux-gnu
      - run:
          name: Install CppCheck
          command: sudo apt-get install -y cppcheck
      - run:
          name: Install gcovr
          command: sudo apt-get install -y gcovr
      - run:
          name: Install clang-format
          command: sudo apt install -y clang-format
      - run:
          name: Make + AddressSanitizer
          command: |
            mkdir tp_iz1/build
            cd tp_iz1/build
            cmake ../ -DCMAKE_BUILD_TYPE=ASAN
            make
      - run:
          name: gcovr
          command: |
            mkdir tp_iz1/coverage
            gcovr -r tp_iz1/ --html -o tp_iz1/coverage/coverage.html --html-details
            cat tp_iz1/coverage/coverage.html
      - store_artifacts:
          path: tp_iz1/coverage/
      - run:
          name: clang-format
          command: |
            cd tp_iz1/src
            clang-format -i -style=WebKit *.c
            cd ../include
            clang-format -i -style=WebKit *.h
            cd ../tests
            clang-format -i -style=WebKit *.cpp
      - run:
          name: Linter
          command: |
            cd tp_iz1/src
            cppcheck *.c
      - run:
          name: Test
          command: |
            cd tp_iz1/build
            ./geometry_test
      - run:
          name: Valgrind
          command: valgrind --tool=memcheck --leak-check=yes tp_iz1/build/geometry_test


