version: 2.1
on:
  push:
    branches:
      - hw-1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - checkout
      - run:
          name: Installing GCC
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc g++
      - run:
          name: Install CMAKE
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake
      - run:
          name: Install Valgrind
          command: sudo apt-get install -y valgrind
      - run:
          name: Install GoogleTests
          command: |
            sudo apt-get install -y libgtest-dev
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp -R /usr/src/gtest/*.a /usr/lib/x86_64-linux-gnu
      - run:
          name: Install CppCheck
          command: sudo apt-get install -y cppcheck
      - run:
          name: Make
          command: |
            mkdir tp_iz1/build
            cd tp_iz1/build
            cmake ../
            make
      - run:
          name: Linter
          command: |
            cd tp_iz1/src
            cppcheck *.c
      - run:
          name: Test
          command: |
            cd tp_iz1/build
            ./geometry_test
      - run:
          name: Valgrind
          command: valgrind --tool=memcheck --leak-check=yes tp_iz1/build/geometry_test
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          # `curl` gets all artifact details for a build
          # then, the result is piped into `grep` to extract the URLs.
          # finally, `wget` is used to download the the artifacts to the current directory in your terminal.

          curl -H "Circle-Token: $48552c96d57709cf04b9256822f2e4cab512b53f" https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/:build_num/artifacts \
                                   | grep -o 'https://[^"]*' \
                                   | wget --verbose --header "Circle-Token: $48552c96d57709cf04b9256822f2e4cab512b53f" --input-file -
