version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - run:
          name: Installing SUDO
          command: |
            sudo apt-get update
            sudo apt-get install -y sudo
            sudo rm -rf /var/lib/apt/lists/*
      - run:
          name: Installing GCC
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc g++
      - run:
          name: Install CMAKE
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake
      - run:
          name: Install Valgrind
          command: sudo apt-get install -y valgrind
      - run:
          name: Install GoogleTests
          command: |
            sudo apt-get install -y googletest
            sudo apt-get install libgtest-dev
      - run:
          name: Install CppCheck
          command: sudo apt-get install -y cppcheck
      - run:
          name: Linter
          command: cd tp_iz1/src && cppcheck *.c
      - run:
          name: Make
          command: |
            mkdir tp_iz1/build
            cd tp_iz1/build
            cmake ../
            make
      - run:
          name: Test
          command: |
            cd tp_iz1/build
            ./geometry_test
      - run:
          name: Valgrind
          command: valgrind --tool=memcheck --leak-check=yes tp_iz1/build/geometru_test
